# API Version: v1
# Purpose: Kubernetes Secrets for Wildlife Detection Safari Pokédex
# Security: AES-256 encryption, strict access controls, automated rotation
# Last Updated: 2024

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: wildlife-detection
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "auth-service"
    vault.hashicorp.com/secret-volume-path: "/vault/secrets"
    secret-rotation-schedule: "90d"
    last-rotated: "2024-01-01T00:00:00Z"
    secret-store: "vault-auth"
type: Opaque
data:
  # JWT signing key - 90-day rotation
  JWT_SECRET_KEY: ${BASE64_JWT_SECRET}
  # Auth0 credentials - 180-day rotation
  AUTH0_CLIENT_ID: ${BASE64_AUTH0_CLIENT_ID}
  AUTH0_CLIENT_SECRET: ${BASE64_AUTH0_CLIENT_SECRET}
  AUTH0_ISSUER_URI: ${BASE64_AUTH0_ISSUER_URI}
  AUTH0_JWK_SET_URI: ${BASE64_AUTH0_JWK_SET_URI}
  # Database credentials - 90-day rotation
  DB_USERNAME: ${BASE64_AUTH_DB_USERNAME}
  DB_PASSWORD: ${BASE64_AUTH_DB_PASSWORD}
  # Encryption keys - 90-day rotation
  ENCRYPTION_KEY: ${BASE64_AUTH_ENCRYPTION_KEY}
  MFA_SECRET_KEY: ${BASE64_MFA_SECRET_KEY}

---
apiVersion: v1
kind: Secret
metadata:
  name: collection-service-secrets
  namespace: wildlife-detection
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "collection-service"
    vault.hashicorp.com/secret-volume-path: "/vault/secrets"
    secret-rotation-schedule: "90d"
    backup-schedule: "24h"
    secret-store: "vault-collection"
type: Opaque
data:
  # Database credentials - 90-day rotation
  DB_USERNAME: ${BASE64_COLLECTION_DB_USERNAME}
  DB_PASSWORD: ${BASE64_COLLECTION_DB_PASSWORD}
  DB_HOST: ${BASE64_COLLECTION_DB_HOST}
  DB_PORT: ${BASE64_COLLECTION_DB_PORT}
  DB_NAME: ${BASE64_COLLECTION_DB_NAME}
  # Encryption keys - 90-day rotation
  ENCRYPTION_KEY: ${BASE64_COLLECTION_ENCRYPTION_KEY}
  BACKUP_ENCRYPTION_KEY: ${BASE64_BACKUP_ENCRYPTION_KEY}

---
apiVersion: v1
kind: Secret
metadata:
  name: detection-service-secrets
  namespace: wildlife-detection
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "detection-service"
    vault.hashicorp.com/secret-volume-path: "/vault/secrets"
    secret-rotation-schedule: "180d"
    rate-limit-policy: "standard"
    secret-store: "vault-detection"
type: Opaque
data:
  # API keys - 180-day rotation
  ML_API_KEY: ${BASE64_ML_API_KEY}
  GBIF_API_KEY: ${BASE64_GBIF_API_KEY}
  INAT_API_KEY: ${BASE64_INAT_API_KEY}
  DINODATA_API_KEY: ${BASE64_DINODATA_API_KEY}
  # ML model protection - 180-day rotation
  MODEL_ENCRYPTION_KEY: ${BASE64_MODEL_ENCRYPTION_KEY}
  API_RATE_LIMIT_KEY: ${BASE64_RATE_LIMIT_KEY}

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secrets
  namespace: wildlife-detection
  annotations:
    cert-manager.io/renewal-window: "720h"
    cert-manager.io/issuer: "letsencrypt-prod"
    secret-store: "vault-tls"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "tls-service"
type: kubernetes.io/tls
data:
  # TLS certificates - Auto-renewed by cert-manager
  tls.crt: ${BASE64_TLS_CERT}
  tls.key: ${BASE64_TLS_KEY}
  ca.crt: ${BASE64_CA_CERT}