platform :ios, '15.0'
use_frameworks!
inhibit_all_warnings!

install_pods_binary_validation = true

def shared_pods
  pod 'TensorFlowLiteSwift', '2.14.0'
  pod 'Alamofire', '5.8.0'
  pod 'SwiftyJSON', '5.0.1'
  pod 'RealmSwift', '10.42.3'
  pod 'SDWebImage', '5.18.3'
  pod 'OpenCV', '4.8.0'
  pod 'ARKit-SCNPath', '1.3.0'
  pod 'Firebase/Analytics', '10.15.0'
  pod 'Sentry', '8.13.1'
end

def testing_pods
  pod 'Quick', '7.3.0'
  pod 'Nimble', '12.3.0'
  pod 'iOSSnapshotTestCase'
end

target 'WildlifeSafari' do
  shared_pods
  pod 'SwiftLint', '0.52.4'
end

target 'WildlifeSafariTests' do
  shared_pods
  testing_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['ENABLE_METAL'] = 'YES'
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
      config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['VALID_ARCHS'] = 'arm64 x86_64'
    end
  end
end